### ISSUE TITLE
IKCE-004 Docker and Project CI/CD Initialization [EPIC]

### ISSUE THREAD

**Issue by anthonysasso2001** [IKC-Reporting/IKC_FullStack_App#9]
Need to setup template Jenkins or other CI/CD for the frontend + backend repo, and integrate with github actions to run on each PR as a validation method. May also need to setup SonarQube as well for this.

- [IKCE-004 Task-000 Initial template and Github Actions Research](https://github.com/IKC-Reporting/IKC_FullStack_App/issues/10).
- [IKCE-004 Task-001 CI/CD Frontend Implementation](https://github.com/IKC-Reporting/IKC_FullStack_App/issues/11).
- [IKCE-004 Task-002 CI/CD Backend Implementation](https://github.com/IKC-Reporting/IKC_FullStack_App/issues/12).

**Comment by tsparks9038** [comment]
Looked into both Jenkins and GitHub Actions. Actions will be easier for us to use for now since it will integrate with the rest of our project, but if we need to switch to Jenkins later migration should be simple.
